Adding angular-http-raml to projects.yml
raml-org/raml-website pull request #55
Opened 2017-08-28 08:27 UTC by erosb

2017-09-29 10:55 UTC, sichvoge commented
@erosb I added a review for your PR. If you'd like to have your project added, please fix my comment and I am happy to merge.

2017-09-29 12:25 UTC, erosb commented
@sichvoge unfortunately I can't find your PR review. Are you sure you added your comments?

2017-09-29 12:35 UTC, sichvoge commented
![image](https://user-images.githubusercontent.com/498114/31016045-67ab7d54-a523-11e7-87f0-9fc8709caa2d.png)

pretty sure ;)

2017-09-29 12:35 UTC, sichvoge requested changes

2017-09-29 12:35 UTC, sichvoge commented on _data/projects.yml
> +  url: "https://github.com/patientsknowbest/angular-http-raml
Can you delete the double quotes here, please?

2017-09-29 12:36 UTC, sichvoge commented
Made it again.

2017-09-29 13:18 UTC, erosb commented
Thanks, I fixed it.

2017-10-10 17:56 UTC, sichvoge approved these changes

2018-06-25 23:54 UTC, jstoiko approved these changes

2018-06-27 20:59 UTC, merged